services:
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun:v3.40.0
    cap_add: [ 'NET_ADMIN' ]
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - OPENVPN_USER=${OPENVPN_USER:?}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD:?}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Switzerland}
    networks:
      main-network:
        ipv4_address: 172.18.0.5
    ports:
      # qbittorrent ports
      - 5080:5080
      - 6881:6881
      - 6881:6881/udp
      # flaresolverr ports
      - 8191:8191
      # jackett-vpn port
      - 9118:9117
    restart: "unless-stopped"

  ## Default credentials of qBittorrent - Username: admin password: adminadmin ##
  ## Change password after install from UI --> Tools --> Options --> WebUI ##
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    depends_on: [ 'vpn' ]
    network_mode: service:vpn
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=UTC
      - WEBUI_PORT=5080
    volumes:
      - qbittorrent-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.1.3
    networks:
      main-network:
        ipv4_address: 172.18.0.2
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=UTC
    ports:
      - 7878:7878
    volumes:
      - radarr-config:/config
      - torrent-downloads:/downloads
    restart: "unless-stopped"

  sonarr:
    image: linuxserver/sonarr:4.0.7
    container_name: sonarr
    networks:
      main-network:
        ipv4_address: 172.18.0.3
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=UTC
    volumes:
      - sonarr-config:/config
      - torrent-downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:1.10.5
    networks:
      main-network:
        ipv4_address: 172.18.0.8
    ports:
      - 9696:9696
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=UTC
    volumes:
      - prowlarr-config:/config
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett:0.22.71
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=UTC
    volumes:
      - jackett-config:/config
    networks:
      main-network:
        ipv4_address: 172.18.0.7
    ports:
      - 9117:9117

  jackett-vpn:
    image: linuxserver/jackett:0.22.71
    container_name: jackett-vpn
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=UTC
    volumes:
      - jackett-vpn-config:/config
    depends_on: [ 'vpn' ]
    network_mode: service:vpn

  flaresolverr:
    image: flaresolverr/flaresolverr:v3.3.19
    container_name: flaresolverr
    restart: unless-stopped
    network_mode: service:vpn
    depends_on: [ 'vpn' ]

  jellyfin:
    image: linuxserver/jellyfin:10.8.12
    container_name: jellyfin
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=UTC
    volumes:
      - jellyfin-config:/config
      - torrent-downloads:/data
    ports:
      - 8096:8096
      - 7359:7359/udp
      - 8920:8920
    networks:
      main-network:
        ipv4_address: 172.18.0.4
    restart: unless-stopped

  reverse-proxy:
    container_name: reverse-proxy
    build: ./reverse-proxy
    ports:
      - 80:80
    volumes:
      - torrent-downloads:/media-files
    restart: unless-stopped
    networks:
      main-network:
        ipv4_address: 172.18.0.6

  media-toolbox:
    container_name: media-toolbox
    build: ./media-toolbox
    volumes:
      - torrent-downloads:/media-files
    restart: unless-stopped

volumes:
  torrent-downloads:
  radarr-config:
  sonarr-config:
  prowlarr-config:
  jellyfin-config:
  qbittorrent-config:
  jackett-config:
  jackett-vpn-config:

networks:
  main-network:
    name: main-network
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
