name: Generate thumbnails for tv show

on:
  workflow_dispatch:
    inputs:
      tv_show_id:
        description: 'The show id for which thumbnails will be generated and published'
        required: true
      season:
        description: 'Season number'
      episode:
        description: 'Episode number'

jobs:
  generate-thumbnails-and-publish:
    runs-on: [ 'self-hosted', 'Linux', X64 ]
    container: q62xyz/transcode:2.2.1
    env:
      AWS_ACCESS_KEY_ID: AKIAQBPWKPTSTP3HL4UM
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-3
      MEDIA_FILES_S3_BUCKET: media-assets-prod-e1pjapsk
      THUMBNAILS_DIR_NAME: thumbnails
      ADMIN_POOL_CLIENT_ID: 2so94a4hnjq3hb38a3km1huf9d
      Q62_ADMIN_USERNAME: rafiksargsyan07@gmail.com
      Q62_ADMIN_PASSWORD: ${{ secrets.Q62_ADMIN_PASSWORD }}
      GET_TV_SHOW_METADATA_ENDPOINT: https://olz10v4b25.execute-api.eu-west-3.amazonaws.com/prod/getTvShowMetadataForPlayer/${{ github.event.inputs.tv_show_id }}/${{ github.event.inputs.season }}/${{ github.event.inputs.episode }}
      TV_SHOW_ID: ${{ github.event.inputs.tv_show_id }}
      SEASON: ${{ github.event.inputs.season }}
      EPISODE: ${{ github.event.inputs.episode }}
      ADD_THUMBNAILS_FILE_TO_TV_SHOW_ENDPOINT: https://olz10v4b25.execute-api.eu-west-3.amazonaws.com/prod/addThumbnailsFileToTvShow
      CF_ENDPOINT: https://dab7e06309a7c1cb8a51557d39d14161.r2.cloudflarestorage.com
      CF_ACCESS_KEY_ID: d2a16978e1e4fb1eb0dcaf352c827c98
      CF_SECRET_ACCESS_KEY: ${{ secrets.PROD_CF_SECRET_ACCESS_KEY }}
      MEDIA_FILES_R2_BUCKET: media-assets-prod-e1pjapsk
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            thumbnails-generator-github-action
            tools

      - name: Setup environment
        run: |
          echo "Q62_AUTH_TOKEN=$(./tools/get-auth-token.sh ${ADMIN_POOL_CLIENT_ID} ${Q62_ADMIN_USERNAME} ${Q62_ADMIN_PASSWORD})" >> $GITHUB_ENV

      - name: Download tv show video file
        run: |
          rm h264_main_540p_18.mp4 || true
          TV_SHOW_METADATA=$(curl ${GET_TV_SHOW_METADATA_ENDPOINT} \
                                -H "Authorization: Bearer ${Q62_AUTH_TOKEN}")                     
          VIDEO_FILE_URL=$(echo $TV_SHOW_METADATA | jq -r '.mpdFile' | sed -e 's/manifest.mpd/h264_main_540p_18.mp4/')
          wget ${VIDEO_FILE_URL}

      - name: Prepare thumbnails directory
        run: |
          mkdir -p ${THUMBNAILS_DIR_NAME}
          rm -r ${THUMBNAILS_DIR_NAME}/* || true

      - name: Generate thumbnails vtt
        uses: ./thumbnails-generator-github-action
        with:
          videoFilePath: "./h264_main_540p_18.mp4"
          outputFolder: "./${{ env.THUMBNAILS_DIR_NAME }}"

      - name: Upload thumbnails assets to S3
        run: |
          for i in 1 2 3; do aws s3 cp "${THUMBNAILS_DIR_NAME}" "s3://${MEDIA_FILES_S3_BUCKET}/${TV_SHOW_ID}/${SEASON}/${EPISODE}/${THUMBNAILS_DIR_NAME}" --recursive && break; done

      - name: Upload transcoding results to R2
        run: |
          for i in 1 2 3; do aws s3 cp "${THUMBNAILS_DIR_NAME}" "s3://${MEDIA_FILES_R2_BUCKET}/${TV_SHOW_ID}/${SEASON}/${EPISODE}/${THUMBNAILS_DIR_NAME}" --endpoint-url  ${CF_ENDPOINT} --recursive  && break; done
        env:
          AWS_ACCESS_KEY_ID: ${{ env.CF_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.CF_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: weur

      - name: Add thumbnails file path to tv show
        run: |
          curl -X PATCH "${ADD_THUMBNAILS_FILE_TO_TV_SHOW_ENDPOINT}" \
               -H "Authorization: Bearer ${Q62_AUTH_TOKEN}" \
               -H "Content-Type: application/json" \
               -d "{\"tvShowId\": \"${TV_SHOW_ID}\", \"relativePath\": \"${TV_SHOW_ID}/${SEASON}/${EPISODE}/${THUMBNAILS_DIR_NAME}/thumbnails.vtt\", \"season\": ${SEASON}, \"episode\": ${EPISODE} }"
