name: Trigger max video quality calculation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  curl_request:
    runs-on: ubuntu-latest

    steps:
      - name: get request to max video quality updater endpoint
        run: |
          curl --header 'Host: www.q62.xyz' -X GET "https://ovh1.q62.xyz/api/updateMaxVideoQuality"
          curl --header 'Host: www.q62.xyz' -X GET "https://ovh2.q62.xyz/api/updateMaxVideoQuality"
